FROM python:3
EXPOSE 5000
ARG /web

COPY . /web/docker-lab0-MariaIsupova-master
WORKDIR /web/docker-lab0-MariaIsupova-master
RUN python3 -m venv venv
RUN . venv/bin/activate
RUN pip install -e .
RUN pip install '.[test]' 
RUN coverage run -m pytest
ENTRYPOINT coverage html
